<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoboCamHub.Domain\RoboCamHub.Domain.csproj" />
    <ProjectReference Include="..\RoboCamHub.NativeInterop\RoboCamHub.NativeInterop.csproj" />
  </ItemGroup>

</Project>
